---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
upload_dir: content/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: true
front_matter_path: "/uploads"
file_template: ":filename:"
version: '0.46'
