---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/fr
  label: French
  create: all
  match: "**/*"
- type: directory
  path: content/en
  label: English
  create: all
  match: "**/*"
- type: directory
  path: content/en
  label: PostsEN
  create: all
  match: posts/**/*
  hidden: true
  templates:
  - test
- type: directory
  path: content/fr
  label: PostsFR
  create: all
  match: posts/**/*
  hidden: true
  templates:
  - test
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.46'
